### ISSUE TITLE
four connect

### ISSUE THREAD

**Issue by Hanspagh** [Jegp/ISP2014#1]
Meget interessante sites
Om four-connect: Hvornår kan man vinde hvornår kan man ikke. 
http://homepages.cwi.nl/~tromp/c4/c4.html

Optimering af alpha-beta-søgning
http://homepages.cwi.nl/~tromp/c4/fhour.html

**Comment by Bladtman242** [comment]
Hey hans.
Minimax returnerer altid -1.
Wat did I do..
Har du tid at lurke hvis jeg pusher en branch op?

Kind regards
Sigurt.

**Comment by Hanspagh** [comment]
Sure, hvis du bruger min implementation + 4x4 bræt, brude du få 0 indtil human begår en fejl. Men bare smid noget op så kigger jeg :D

**Comment by Bladtman242** [comment]
Pushet.
Han duden i dit link har lavet en 8-ply db man kan hente..

Kind regards
Sigurt.

**Comment by Hanspagh** [comment]
Jeg er ikke helt sikker, men det tror jeg. Jeg har mest kigget på implementation af alpha-beta-search med lookup tables og noget de kalder history heuristics.

**Comment by Bladtman242** [comment]
Ikke sikker på hvad? :)
Han har lagt databasen op.
Har du kigget på den ringe kode jeg har produceret? :)

Kind regards
Sigurt.

**Comment by Hanspagh** [comment]
Ja, men det var mere om det var i et format man kunne bruge til noget. :D. 
Ja, jeg forstår ikke hvordan den kan returnere -1?
er det float min value?

**Comment by Bladtman242** [comment]
Nej, int bestAction.
minimax funktionen finder aldrig et min der er større end Float.MIN_VALUE.
Jeg kan ikke helt lure hvad jeg har gjort galt, koden er næsten magen til
din, bare med floats i stedet for ints for utility værdier, og cutoff.

Kind regards
Sigurt.

**Comment by Hanspagh** [comment]
Meget underligt, den burde altid finde noget bedre en Float.Min_Value, da både utility og h returner floats over det? Har du undersøgt om din h værdi rent faktisk bliver returneret?

**Comment by Bladtman242** [comment]
Ikke rigtigt, men det burde den :)
Jeg tjekker lige, og hvis det ikke er det tager vi den bare torsdag, så
tester jeg heuristikken uden minimax :)

Kind regards
Sigurt.

2014-02-25 14:53 GMT+01:00 Hans notifications@github.com:

**Comment by Bladtman242** [comment]
Det gør den...

Kind regards
Sigurt.

2014-02-25 14:55 GMT+01:00 Sigurt Dinesen sigurt91@gmail.com:

**Comment by Hanspagh** [comment]
Jeg kan ikke se noget forkert ved det du har lavet, så der skal nok debugging til. Vi ser på det torsdag :D

**Comment by Bladtman242** [comment]
Yepper.
Tak for sparring :)

Kind regards
Sigurt.

**Comment by Hanspagh** [comment]
Problemet er at Float.Min_Value ikke retunere et negativts tal, blot et meget lille tal :D

**Comment by Bladtman242** [comment]
Godt spottet Hans!

Kind regards
Sigurt.
